pipeline{
    agent{
        label "nodejs"
    }
    stages{
  
         stage('Deploy') {
            steps {
                sh '''
                    oc project eyrptl-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
